### ISSUE TITLE
exportUserProfile error

### ISSUE THREAD

**Issue by alexio777** [ulixee/hero#135]
Hi,
Sometimes when I do a profile export I get an error:

```
0708-1647[00.0]: 2022-07-08T14:47:27.186Z ERROR [hero-core/connections/ConnectionToClient] ConnectionToClient.HandleRequestError {
0708-1647[00.0]:   context: {},
0708-1647[00.0]:   sessionId: 'KABnJhLvybiwsuDY4COcj',
0708-1647[00.0]:   sessionName: 'default-session'
0708-1647[00.0]: } TypeError: window.exportDomStorage is not a function
0708-1647[00.0]:     at <anonymous>:1:8
0708-1647[00.0]: ERROR2!
0708-1647[00.0]: TypeError: window.exportDomStorage is not a function
0708-1647[00.0]:     at <anonymous>:1:8
0708-1647[00.0]: ------CONNECTION----------------------------------
0708-1647[00.0]:     at new Resolvable (/home/alexio/fs/test/node_modules/@ulixee/hero/node_modules/commons/lib/Resolvable.ts:16:18)
0708-1647[00.0]:     at createPromise (/home/alexio/fs/test/node_modules/@ulixee/hero/node_modules/commons/lib/utils.ts:146:10)
0708-1647[00.0]:     at ConnectionToLocalCore.createPendingResult (/home/alexio/fs/test/node_modules/client/connections/ConnectionToCore.ts:363:44)
0708-1647[00.0]:     at ConnectionToLocalCore.internalSendRequestAndWait (/home/alexio/fs/test/node_modules/client/connections/ConnectionToCore.ts:269:43)
0708-1647[00.0]:     at ConnectionToLocalCore.sendRequest (/home/alexio/fs/test/node_modules/client/connections/ConnectionToCore.ts:165:17)
0708-1647[00.0]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0708-1647[00.0]:     at async CoreCommandQueue.sendRequest (/home/alexio/fs/test/node_modules/client/lib/CoreCommandQueue.ts:287:22)
0708-1647[00.0]:     at async Object.cb (/home/alexio/fs/test/node_modules/client/lib/CoreCommandQueue.ts:229:16)
0708-1647[00.0]:     at async Queue.next (/home/alexio/fs/test/node_modules/@ulixee/hero/node_modules/commons/lib/Queue.ts:95:19)
0708-1647[00.0]: ------CORE COMMANDS-------------------------------
0708-1647[00.0]:     at Queue.run (/home/alexio/fs/test/node_modules/@ulixee/hero/node_modules/commons/lib/Queue.ts:40:19)
0708-1647[00.0]:     at CoreCommandQueue.run (/home/alexio/fs/test/node_modules/client/lib/CoreCommandQueue.ts:218:8)
0708-1647[00.0]:     at CoreTab.exportUserProfile (/home/alexio/fs/test/node_modules/client/lib/CoreTab.ts:273:36)
0708-1647[00.0]:     at Hero.exportUserProfile (/home/alexio/fs/test/node_modules/client/lib/Hero.ts:342:26)
0708-1647[00.0]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0708-1647[00.0]: 
0708-1647[00.0]: --------------------------------------------------
0708-1647[00.0]: ------default-session-----------------------------
0708-1647[00.0]: ------KABnJhLvybiwsuDY4COcj-----------------------
0708-1647[00.0]: -------------------------------------------------- {
```

**Comment by alexio777** [comment]
And sometimes I see this:

```
0710-1048[00.0]: } ["DOMException: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.\n    at window.exportDomStorage (<anonymous>:790:35)\n    at <anonymous>:1:8({ stack: undefined, code: 18, name: SecurityError, message: Failed to read the 'localStorage' property from 'W…sandboxed and lacks the 'allow-same-origin' flag. })"]
0710-1048[00.0]: ERROR2!
0710-1048[00.0]: "DOMException: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.\n    at window.exportDomStorage (<anonymous>:790:35)\n    at <anonymous>:1:8({ stack: undefined, code: 18, name: SecurityError, message: Failed to read the 'localStorage' property from 'W…sandboxed and lacks the 'allow-same-origin' flag. })"
0710-1048[00.0]: ------CONNECTION----------------------------------
0710-1048[00.0]:     at new Resolvable (/app/node_modules/@ulixee/hero/node_modules/commons/lib/Resolvable.ts:16:18)
0710-1048[00.0]:     at createPromise (/app/node_modules/@ulixee/hero/node_modules/commons/lib/utils.ts:146:10)
0710-1048[00.0]:     at ConnectionToLocalCore.createPendingResult (/app/node_modules/client/connections/ConnectionToCore.ts:363:44)
0710-1048[00.0]:     at ConnectionToLocalCore.internalSendRequestAndWait (/app/node_modules/client/connections/ConnectionToCore.ts:269:43)
0710-1048[00.0]:     at ConnectionToLocalCore.sendRequest (/app/node_modules/client/connections/ConnectionToCore.ts:165:17)
0710-1048[00.0]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0710-1048[00.0]:     at async CoreCommandQueue.sendRequest (/app/node_modules/client/lib/CoreCommandQueue.ts:287:22)
0710-1048[00.0]:     at async Object.cb (/app/node_modules/client/lib/CoreCommandQueue.ts:229:16)
0710-1048[00.0]:     at async Queue.next (/app/node_modules/@ulixee/hero/node_modules/commons/lib/Queue.ts:95:19)
0710-1048[00.0]: ------CORE COMMANDS-------------------------------
0710-1048[00.0]:     at Queue.run (/app/node_modules/@ulixee/hero/node_modules/commons/lib/Queue.ts:40:19)
0710-1048[00.0]:     at CoreCommandQueue.run (/app/node_modules/client/lib/CoreCommandQueue.ts:218:8)
0710-1048[00.0]:     at CoreTab.exportUserProfile (/app/node_modules/client/lib/CoreTab.ts:273:36)
0710-1048[00.0]:     at Hero.exportUserProfile (/app/node_modules/client/lib/Hero.ts:342:26)
0710-1048[00.0]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
