### ISSUE TITLE
ECONNRESET | Chrome failed to start

### ISSUE THREAD

**Issue by loss-and-quick** [ulixee/hero#196]
There is my code
```
    const miner = new Miner();
    await miner.listen();
    const torConnection = await connect({
        host: '127.0.0.1',
        port:controlPort,
        password: 'qwerty', 
    });

    const fingerprint=worker.browserFingerprint.fingerprint
    const hero = new Hero({
        name:`${worker.telegramID}`,
        connectionToCore: { host:`${await miner.address}` },
        showChrome:true,
        userAgent:fingerprint.navigator.userAgent,
        viewport:fingerprint.screen,
        locale:fingerprint.navigator.language,
        // upstreamProxyUrl:`http://127.0.0.1:${proxyPort}`,
        // upstreamProxyIpMask:{
        //     publicIp:(await tor.getInfo(torConnection,['address'])).address
        // }
    });
    await hero.goto(link);
    await sleep(40000);
```

logs:
```

2022-11-23T19:23:12.460Z ERROR [unblocked-agent/lib/PipeTransport] PipeTransport.WriteError { context: {}, sessionId: null, sessionName: undefined } Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:217:20)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
2022-11-23T19:23:12.497Z ERROR [hero-core/connections/ConnectionToHeroClient] ConnectionToClient.HandleRequestError { context: {}, sessionId: undefined, sessionName: undefined } BrowserLaunchError: CanceledPromiseError: Cancel Pending Promise (Target.setAutoAttach): Target closed.
    at DevtoolsSession.onClosed (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/DevtoolsSession.ts:129:21)
    at Connection.onClosed (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Connection.ts:93:15)
    at PipeTransport.onReadClosed (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/PipeTransport.ts:85:42)
    at Socket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:313:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
------DEVTOOLS------------------------------------
------DEVTOOLS_SESSION_ID=------------------------
    at new Resolvable (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Resolvable.ts:16:18)
    at createPromise (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/utils.ts:168:10)
    at DevtoolsSession.send (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/DevtoolsSession.ts:79:37)
    at Browser.testConnection (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Browser.ts:223:32)
    at Browser.launch (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Browser.ts:104:33)
    at async Object.cb (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Pool.ts:141:7)
    at async Queue.next (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:95:19)
------BROWSER_CREATION_Q--------------------------
    at Queue.run (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:40:19)
    at Pool.getBrowser (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Pool.ts:124:44)
    at Agent.open (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Agent.ts:107:34)
    at async Session.openBrowser (/home/minicx/prog/nodejs/hk_bot/node_modules/core/lib/Session.ts:389:5)
    at async Function.create (/home/minicx/prog/nodejs/hk_bot/node_modules/core/lib/Session.ts:878:7)
    at async ConnectionToHeroClient.createSession (/home/minicx/prog/nodejs/hk_bot/node_modules/core/connections/ConnectionToHeroClient.ts:187:30)
    at async CommandRunner.runFn (/home/minicx/prog/nodejs/hk_bot/node_modules/core/lib/CommandRunner.ts:36:14)
    at async ConnectionToHeroClient.executeCommand (/home/minicx/prog/nodejs/hk_bot/node_modules/core/connections/ConnectionToHeroClient.ts:249:12)
    at async ConnectionToHeroClient.handleRequest (/home/minicx/prog/nodejs/hk_bot/node_modules/core/connections/ConnectionToHeroClient.ts:64:14) {
  isSandboxError: false
}
2022-11-23T19:23:13.293Z ERROR [hero-core/index] UnhandledErrorOrRejection { context: {}, sessionId: null, sessionName: undefined } Error [BrowserLaunchError]: CanceledPromiseError: Ulixee Miner failed to launch Chrome - Cancel Pending Promise (Target.setAutoAttach): Target closed.. See Miner console logs for details.
    at DevtoolsSession.onClosed (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/DevtoolsSession.ts:129:21)
    at Connection.onClosed (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Connection.ts:93:15)
    at PipeTransport.onReadClosed (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/PipeTransport.ts:85:42)
    at Socket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:313:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
------DEVTOOLS------------------------------------
------DEVTOOLS_SESSION_ID=------------------------
    at new Resolvable (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Resolvable.ts:16:18)
    at createPromise (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/utils.ts:168:10)
    at DevtoolsSession.send (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/DevtoolsSession.ts:79:37)
    at Browser.testConnection (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Browser.ts:223:32)
    at Browser.launch (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Browser.ts:104:33)
    at async Object.cb (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Pool.ts:141:7)
    at async Queue.next (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:95:19)
------BROWSER_CREATION_Q--------------------------
    at Queue.run (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:40:19)
    at Pool.getBrowser (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Pool.ts:124:44)
    at Agent.open (/home/minicx/prog/nodejs/hk_bot/agent/core/lib/Agent.ts:107:34)
    at async Session.openBrowser (/home/minicx/prog/nodejs/hk_bot/node_modules/core/lib/Session.ts:389:5)
    at async Function.create (/home/minicx/prog/nodejs/hk_bot/node_modules/core/lib/Session.ts:878:7)
    at async ConnectionToHeroClient.createSession (/home/minicx/prog/nodejs/hk_bot/node_modules/core/connections/ConnectionToHeroClient.ts:187:30)
    at async CommandRunner.runFn (/home/minicx/prog/nodejs/hk_bot/node_modules/core/lib/CommandRunner.ts:36:14)
    at async ConnectionToHeroClient.executeCommand (/home/minicx/prog/nodejs/hk_bot/node_modules/core/connections/ConnectionToHeroClient.ts:249:12)
    at async ConnectionToHeroClient.handleRequest (/home/minicx/prog/nodejs/hk_bot/node_modules/core/connections/ConnectionToHeroClient.ts:64:14)
------REMOTE CORE---------------------------------
    at Function.reviver (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/TypeSerializer.ts:242:26)
    at JSON.parse (<anonymous>)
    at Function.parse (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/TypeSerializer.ts:31:17)
    at WsTransportToCore.onMessage (/home/minicx/prog/nodejs/hk_bot/node_modules/net/lib/WsTransportToCore.ts:111:36)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/minicx/prog/nodejs/hk_bot/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/minicx/prog/nodejs/hk_bot/node_modules/ws/lib/receiver.js:517:14)
    at /home/minicx/prog/nodejs/hk_bot/node_modules/ws/lib/receiver.js:468:23
    at /home/minicx/prog/nodejs/hk_bot/node_modules/ws/lib/permessage-deflate.js:308:9
------CONNECTION----------------------------------
    at new Resolvable (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Resolvable.ts:16:18)
    at createPromise (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/utils.ts:168:10)
    at PendingMessages.create (/home/minicx/prog/nodejs/hk_bot/node_modules/net/lib/PendingMessages.ts:47:44)
    at ConnectionToHeroCore.sendRequest (/home/minicx/prog/nodejs/hk_bot/node_modules/net/lib/ConnectionToCore.ts:153:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CoreCommandQueue.sendRequest (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/CoreCommandQueue.ts:287:12)
    at async Object.cb (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/CoreCommandQueue.ts:229:16)
    at async Queue.next (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:95:19)
------CORE COMMANDS-------------------------------
    at Queue.run (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:40:19)
    at CoreCommandQueue.run (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/CoreCommandQueue.ts:218:8)
    at Object.cb (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/CoreSessions.ts:31:64)
    at Queue.next (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:95:44)
    at Queue.run (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:43:10)
    at CoreSessions.create (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/CoreSessions.ts:30:8)
    at ConnectionToHeroCore.createSession (/home/minicx/prog/nodejs/hk_bot/node_modules/client/connections/ConnectionToHeroCore.ts:57:38)
    at Hero._Hero_getCoreSessionOrReject (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/Hero.ts:591:10)
    at Hero.get activeTab [as activeTab] (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/Hero.ts:146:33)
    at Hero.goto (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/Hero.ts:430:17)
------AGENT QUEUE---------------------------------
    at Queue.run (/home/minicx/prog/nodejs/hk_bot/node_modules/commons/lib/Queue.ts:40:19)
    at CoreSessions.create (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/CoreSessions.ts:30:8)
    at ConnectionToHeroCore.createSession (/home/minicx/prog/nodejs/hk_bot/node_modules/client/connections/ConnectionToHeroCore.ts:57:38)
    at Hero._Hero_getCoreSessionOrReject (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/Hero.ts:591:10)
    at Hero.get activeTab [as activeTab] (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/Hero.ts:146:33)
    at Hero.goto (/home/minicx/prog/nodejs/hk_bot/node_modules/client/lib/Hero.ts:430:17)
    at vertification (/home/minicx/prog/nodejs/hk_bot/utils.js:31:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doTasks (/home/minicx/prog/nodejs/hk_bot/index.js:256:25) {
  isSandboxError: false
}
```

**Comment by loss-and-quick** [comment]
After cleaning `~/.cache`,deleting `node-modules` and installing packages again,hero started working
