### ISSUE TITLE
(intermediate value).addEventListener is not a function

### ISSUE THREAD

**Issue by soundofspace** [ulixee/hero#203]
I see this error happening a lot, don't really know why.
In discord this was mention `It kind of looks like a Hero instance getting shutdown mid-creation`, which could definitely happen since there are timeouts on everything, and case something is not fast enough, the instance is closed, and so is hero. This might mean a hero is closed while the core is still doing something on it? This does not seem to crash the core and could probably be ignored, or even better should detect a close, and don't do this.
```
TypeError: (intermediate value).addEventListener is not a function
    at Tab.addEventListener (/app/service/.yarn/cache/@ulixee-hero-npm-2.0.0-alpha.16-dcd2a28d00-4cf8e995f3.zip/node_modules/client/lib/AwaitedEventTarget.ts:17:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-12-07T13:11:28.173Z ERROR [hero-core/index] UnhandledRejection { context: {}, sessionId: null, sessionName: undefined } TypeError: (intermediate value).addEventListener is not a function
    at Tab.addEventListener (/app/service/.yarn/cache/@ulixee-hero-npm-2.0.0-alpha.16-dcd2a28d00-4cf8e995f3.zip/node_modules/client/lib/AwaitedEventTarget.ts:17:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: (intermediate value).addEventListener is not a function
    at Tab.addEventListener (/app/service/.yarn/cache/@ulixee-hero-npm-2.0.0-alpha.16-dcd2a28d00-4cf8e995f3.zip/node_modules/client/lib/AwaitedEventTarget.ts:17:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: (intermediate value).addEventListener is not a function
    at Tab.addEventListener (/app/service/.yarn/cache/@ulixee-hero-npm-2.0.0-alpha.16-dcd2a28d00-4cf8e995f3.zip/node_modules/client/lib/AwaitedEventTarget.ts:17:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by soundofspace** [comment]
Probably similar to #204

**Comment by blakebyrnes** [comment]
Have a fix for this one in latest unblocked. Let's re-test with the next release.

**Comment by blakebyrnes** [comment]
No, I don't think they're related. #204 is in Core.

**Comment by blakebyrnes** [comment]
This is in version 2.0.0-alpha.17

**Comment by blakebyrnes** [comment]
@soundofspace  Is this resolved?

**Comment by soundofspace** [comment]
@blakebyrnes yes it is, sorry forgot about this.
