### ISSUE TITLE
Target for command not available (Events)

### ISSUE THREAD

**Issue by soundofspace** [ulixee/hero#204]
See this error happening pretty much all the time. I think this happens when a hero instance, together with its connections is closed and the core is still doing some cleanup/work. This should detect a close and stop/ignore this. This is probably related to #203 

```
Error: Target for command not available (Events)
    at new CommandRunner (/app/.yarn/cache/@ulixee-hero-core-npm-2.0.0-alpha.16-b4152c72e1-55ca8f31a6.zip/node_modules/[4mcore[24m/lib/CommandRunner.ts:16:13)
    at ConnectionToHeroClient.executeCommand (/app/.yarn/cache/@ulixee-hero-core-npm-2.0.0-alpha.16-b4152c72e1-55ca8f31a6.zip/node_modules/[4mcore[24m/connections/ConnectionToHeroClient.ts:236:27)
    at ConnectionToHeroClient.handleRequest (/app/.yarn/cache/@ulixee-hero-core-npm-2.0.0-alpha.16-b4152c72e1-55ca8f31a6.zip/node_modules/[4mcore[24m/connections/ConnectionToHeroClient.ts:63:25)
    at EmittingTransportToClient.<anonymous> (/app/.yarn/cache/@ulixee-hero-core-npm-2.0.0-alpha.16-b4152c72e1-55ca8f31a6.zip/node_modules/[4mcore[24m/connections/ConnectionToHeroClient.ts:43:45)"
```

**Comment by blakebyrnes** [comment]
Do you have a session database showing this error? Also, is this just a matter of this logging to logs? Or is it crashing something?

**Comment by soundofspace** [comment]
It was a logging issue. But upgrading to 2.0.0-alpha.17 seems to have fixed this.

**Comment by soundofspace** [comment]
Actually it is still popping up quite a lot. Will upgrade to latest version next week, and if it is still there I will provide a session db.
