### ISSUE TITLE
http(s) Proxy error.

### ISSUE THREAD

**Issue by ErenKrt** [ulixee/hero#208]
Hello, im trying use Hero with http proxy. I checked my proxy from online checkers and local program its work. But not working on Hero

```js
const {default: Hero} = require('@ulixee/hero-playground');
const username="";
const password="";
const ip="";
const port="";

(async () => {

  const hero = new Hero({
    showChrome: true,
    showDevtools: false,
    upstreamProxyUrl: 'http://${username}:${password}@${ip}:${port}',
    showChrome: true,
  });

  await hero.goto('http://example.com');
  await hero.activeTab.waitForLoad('AllContentLoaded');
  await hero.close();
})();
```

I got these errors

```
2022-12-25T11:32:16.420Z ERROR [hero-core\connections\ConnectionToHeroClient] ConnectionToClient.HandleRequestError { context: {}, sessionId: undefined, sessionName: undefined } HttpProxyConnectError: connection refused (502)
<html><head><title>502 Bad Gateway</title></head>
<body><h2>502 Bad Gateway</h2><h3>Host Not Found or connection failed</h3></body></html>
    at buildConnectError (C:\Users\Me\Documents\GitHub\test\agent\mitm-socket\index.ts:277:13)
    at MitmSocket.triggerConnectErrorIfNeeded (C:\Users\Me\Documents\GitHub\test\agent\mitm-socket\index.ts:226:7)
    at MitmSocket.onError (C:\Users\Me\Documents\GitHub\test\agent\mitm-socket\index.ts:249:12)
    at MitmSocket.onMessage (C:\Users\Me\Documents\GitHub\test\agent\mitm-socket\index.ts:202:12)
    at MitmSocketSession.onMessage (C:\Users\Me\Documents\GitHub\test\agent\mitm-socket\lib\MitmSocketSession.ts:48:41)
    at MitmSocketSession.onIpcData (C:\Users\Me\Documents\GitHub\test\agent\mitm-socket\lib\BaseIpcHandler.ts:165:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
```

**Comment by blakebyrnes** [comment]
Temporary workaround appears to be to pre-configure the `upstreamProxyMask` due to issues with ipify.

```
 const hero = new Hero({
    showChrome: true,
    showDevtools: false,
    upstreamProxyUrl: 'http://${username}:${password}@${ip}:${port}',
    upstreamProxyMask: {
       publicIp: 'my machine ip',
       proxyIp: 'proxy ip'
    },
    showChrome: true,
  });
```

Longterm, I'm not sure what we should do here. For most proxies, we're actually faking out that the proxy will function over UDP (for webrtc). There's a chrome setting to block udp if not sent through the proxy, but since there's not really ump proxy support in Chrome (to my knowledge), this seems like it creates a way to detect a proxy is in use.  

In the interim, we should probably make upstreamProxyMask opt-in and/or host a bare-bones public ip service. It can be part of a clustered Miner host as well so you don't have to rely on a central service. We'll eventually need to know your public ip when you host a Miner that connects to the broader cloud. Any ideas here @calebjclark?
