### ISSUE TITLE
hero/connections/ConnectionFactory

### ISSUE THREAD

**Issue by benhichem** [ulixee/hero#230]
so i have been using hero for the past year or so and lately when i install the @ulixee/hero & @ulixee/server package and lunch it like i usually and how its written in the documentation do am getting this error if anyone can help me solve this one i would be great full 

@blakebyrnes  @calebjclark @GlenDC @daleevans @jmannanc 
the error : 

 `2023-05-13T14:40:13.509Z ERROR [hero/connections/ConnectionFactory] Error connecting to core { context: {}, sessionId: null, sessionName: undefined } CanceledPromiseError: Websocket was not open
    at wsSend (/workspaces/CF-bigspy/node_modules/net/lib/WsUtils.ts:15:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WsTransportToCore.send (/workspaces/CF-bigspy/node_modules/net/lib/WsTransportToCore.ts:52:7)
    at async Promise.all (index 1)
    at async ConnectionToHeroCore.sendRequest (/workspaces/CF-bigspy/node_modules/net/lib/ConnectionToCore.ts:158:24)
    at async ConnectionToHeroCore.afterConnect (/workspaces/CF-bigspy/node_modules/client/connections/ConnectionToHeroCore.ts:87:27)
    at async ConnectionToHeroCore.connect (/workspaces/CF-bigspy/node_modules/net/lib/ConnectionToCore.ts:83:11)
2023-05-13T14:40:13.514Z ERROR [hero-core/index] UnhandledError(fatal) { context: {}, sessionId: null, sessionName: undefined } CanceledPromiseError: Websocket was not open
    at wsSend (/workspaces/CF-bigspy/node_modules/net/lib/WsUtils.ts:15:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WsTransportToCore.send (/workspaces/CF-bigspy/node_modules/net/lib/WsTransportToCore.ts:52:7)
    at async Promise.all (index 1)
    at async ConnectionToHeroCore.sendRequest (/workspaces/CF-bigspy/node_modules/net/lib/ConnectionToCore.ts:158:24)
    at async ConnectionToHeroCore.afterConnect (/workspaces/CF-bigspy/node_modules/client/connections/ConnectionToHeroCore.ts:87:27)
    at async ConnectionToHeroCore.connect (/workspaces/CF-bigspy/node_modules/net/lib/ConnectionToCore.ts:83:11)
------CORE COMMANDS-------------------------------
    at Queue.run (/workspaces/CF-bigspy/node_modules/commons/lib/Queue.ts:40:19)
    at CoreCommandQueue.run (/workspaces/CF-bigspy/node_modules/client/lib/CoreCommandQueue.ts:220:8)
    at Object.cb (/workspaces/CF-bigspy/node_modules/client/lib/CoreSessions.ts:35:64)
    at Queue.next (/workspaces/CF-bigspy/node_modules/commons/lib/Queue.ts:98:44)
    at Queue.run (/workspaces/CF-bigspy/node_modules/commons/lib/Queue.ts:43:10)
    at CoreSessions.create (/workspaces/CF-bigspy/node_modules/client/lib/CoreSessions.ts:34:8)
    at ConnectionToHeroCore.createSession (/workspaces/CF-bigspy/node_modules/client/connections/ConnectionToHeroCore.ts:67:38)
    at Hero._Hero_getCoreSessionOrReject (/workspaces/CF-bigspy/node_modules/client/lib/Hero.ts:686:10)
    at Hero.get activeTab [as activeTab] (/workspaces/CF-bigspy/node_modules/client/lib/Hero.ts:174:33)
    at Hero.goto (/workspaces/CF-bigspy/node_modules/client/lib/Hero.ts:465:17)
------AGENT QUEUE---------------------------------
    at Queue.run (/workspaces/CF-bigspy/node_modules/commons/lib/Queue.ts:40:19)
    at CoreSessions.create (/workspaces/CF-bigspy/node_modules/client/lib/CoreSessions.ts:34:8)
    at ConnectionToHeroCore.createSession (/workspaces/CF-bigspy/node_modules/client/connections/ConnectionToHeroCore.ts:67:38)
    at Hero._Hero_getCoreSessionOrReject (/workspaces/CF-bigspy/node_modules/client/lib/Hero.ts:686:10)
    at Hero.get activeTab [as activeTab] (/workspaces/CF-bigspy/node_modules/client/lib/Hero.ts:174:33)
    at Hero.goto (/workspaces/CF-bigspy/node_modules/client/lib/Hero.ts:465:17)
    at X.$extract (file:///workspaces/CF-bigspy/src/index.js:65:24)
    at X.exec (file:///workspaces/CF-bigspy/src/index.js:54:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///workspaces/CF-bigspy/src/index.js:72:1

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(`

**Comment by blakebyrnes** [comment]
The @ulixee/server package got renamed to @ulixee/cloud, so you're likely running on a version that's a few versions old. I think you're hitting a bug that we used to have here the cache directory/ulixee/hosts.json file wasn't getting cleaned up properly. You could try just deleting that file, or updating

**Comment by benhichem** [comment]
well the same thing ! after installing @ulixee/cloud am getting this error now ... 

`
Default Datastore Plugin not installed @ulixee/datastore-plugins-puppeteer-core/register Cannot find module '@ulixee/datastore-plugins-puppeteer-core/register'
Require stack:
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CoreRouter.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CloudNode.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/index.js
2023-05-13T17:48:39.122Z ERROR [hero-core/index] UnhandledRejection { context: {}, sessionId: null, sessionName: undefined } Error: Cannot find module 'vm2'
Require stack:
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/datastore-plugins-hero-core/index.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/datastore-plugins-hero-core/register.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CoreRouter.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CloudNode.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at DatastoreForHeroPluginCore.onCoreStart (/home/snow/Desktop/fiverr/AP_Crawler/datastore/plugins/hero-core/index.ts:60:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.start (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/datastore/core/index.ts:256:33)
    at async CoreRouter.start (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/cloud/main/lib/CoreRouter.ts:125:7)
    at async CloudNode.listen (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/cloud/main/lib/CloudNode.ts:118:7)
    at async Index.$setup (file:///home/snow/Desktop/fiverr/AP_Crawler/apcrawler/dist/hero_client.js:25:9)
    at async Index.exec (file:///home/snow/Desktop/fiverr/AP_Crawler/apcrawler/dist/hero_client.js:51:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/datastore-plugins-hero-core/index.js',
    '/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/datastore-plugins-hero-core/register.js',
    '/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CoreRouter.js',
    '/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CloudNode.js',
    '/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/index.js'
  ]
}

`

**Comment by blakebyrnes** [comment]
That warning message shouldn't be there... got added during last round of development. But the actual error there looks like a module didn't get installed correctly. Did you have errors during installation?

**Comment by benhichem** [comment]
i had few warning showing during installation yes !! 
" 4 critical severity vulnerabilities "

and after running npm audit 
 
`
vm2  <3.9.17
Severity: critical
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-ch3r-j5x3-6q2m
fix available via `npm audit fix --force`
Will install undefined@undefined, which is a breaking change
node_modules/@ulixee/datastore-core/node_modules/vm2
  @ulixee/datastore-core  *
  Depends on vulnerable versions of vm2
  node_modules/@ulixee/datastore-core
    @ulixee/cloud  *
    Depends on vulnerable versions of @ulixee/datastore-core
    Depends on vulnerable versions of @ulixee/datastore-plugins-hero-core
    node_modules/@ulixee/cloud
    @ulixee/datastore-plugins-hero-core  *
    Depends on vulnerable versions of @ulixee/datastore-core
    node_modules/@ulixee/datastore-plugins-hero-core

4 critical severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
`

**Comment by blakebyrnes** [comment]
Hmm. I have a pending commit to that repo that the security audit fix seems to have unlinked from our vm2.. I tried re-synching their repo. Maybe that will fix it if you try again.

**Comment by benhichem** [comment]
i have deleted and reinstalled everything again and now there is a new error showing 
![image](https://github.com/ulixee/hero/assets/77390862/5e4f41d2-8df4-4fe3-b1b1-88fc4bf18f48)

**Comment by benhichem** [comment]
i have deleted and reinstalled everything again and now there is a new error showing 
![image](https://github.com/ulixee/hero/assets/77390862/5e4f41d2-8df4-4fe3-b1b1-88fc4bf18f48)

**Comment by blakebyrnes** [comment]
Sorry this is so nasty with that console.warn!! Will remove that in next version. This appears to actually just be an issue with your Chrome being unable to launch, so sorry for the hassle of updating Hero, but thanks for helping identity those 2 issues. If you're on linux, occasionally you need to install Chrome shared-library dependencies to get it working (or they change out underneath). Are there any detailed logs indicating why Chrome closed?

**Comment by benhichem** [comment]
this is the rest of the error,  i will update my chrome and then see how is up !  
![image](https://github.com/ulixee/hero/assets/77390862/c44955e5-41e8-4b55-843f-71a4567f78fa)

**Comment by blakebyrnes** [comment]
The message should be on the CloudNode side

**Comment by benhichem** [comment]
where can i find them ?

**Comment by benhichem** [comment]
where can i find them ?

**Comment by blakebyrnes** [comment]
I just realized you're starting Cloud and Hero in the same process. You might see something by starting with DEBUG=ulx* as an env var

**Comment by blakebyrnes** [comment]
There's a dependency installer for your Chrome version at ~/.cache/ulixee/chromes/<version>/install-dependencies.deb

**Comment by benhichem** [comment]
well i have installed the Chrome versions from the path you provided 
and DEBUG=ulx* 

its the same error tho :
`

Default Datastore Plugin not installed @ulixee/datastore-plugins-puppeteer-core/register Cannot find module '@ulixee/datastore-plugins-puppeteer-core/register'
Require stack:
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CoreRouter.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/lib/CloudNode.js
- /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/@ulixee/cloud/index.js
2023-05-13T18:46:47.421Z INFO [cloud/lib/CoreRouter] CloudNode.start { cloudNodeAddress: 'localhost:6450', context: {} }
2023-05-13T18:46:47.427Z INFO [hero-core/index] Core.start { options: { shouldShutdownOnSignals: true }, context: {} }
2023-05-13T18:46:47.467Z INFO [unblocked-agent/lib/Pool] Pool.start { context: {} }
2023-05-13T18:46:47.507Z INFO [hero-core/index] Core started { dataDir: '/tmp/.ulixee', context: {} }
2023-05-13T18:46:47.510Z INFO [datastore-core/index] DatastoreCore.start {
  options: {
    serverEnvironment: 'development',
    datastoresDir: '/home/snow/.cache/ulixee/datastores',
    datastoresTmpDir: '/tmp/.ulixee/datastore',
    maxRuntimeMs: 600000,
    waitForDatastoreCompletionOnShutdown: false,
    enableDatastoreWatchMode: true,
    paymentAddress: undefined,
    requireDatastoreAdminIdentities: false,
    cloudAdminIdentities: [],
    computePricePerQuery: 0,
    defaultBytesForPaymentEstimates: 256,
    approvedSidechains: [],
    defaultSidechainHost: undefined,
    defaultSidechainRootIdentity: undefined,
    identityWithSidechain: undefined,
    approvedSidechainsRefreshInterval: 3600000
  },
  context: {}
}
2023-05-13T18:46:47.574Z STATS [datastore-core/index] DatastoreCore.started { context: {} }
2023-05-13T18:46:47.578Z STATS [cloud/lib/CoreRouter] CloudNode.started { context: {} }
2023-05-13T18:46:47.675Z INFO [hero/connections/ConnectionToHeroCore] Overriding max concurrency with Core value { maxConcurrency: 10, context: {} }
2023-05-13T18:46:47.907Z INFO [unblocked-agent/lib/Agent] Agent created {
  id: 'dzTjDmn7DXs7etiPtT_3K',
  incognito: true,
  hasHooks: true,
  browserEngine: { fullVersion: '112.0.5615.121' },
  context: { sessionId: 'dzTjDmn7DXs7etiPtT_3K' }
}
2023-05-13T18:46:47.919Z INFO [unblocked-agent/lib/Pool] Pool.waitForAvailability {
  maxConcurrentAgents: 10,
  activeAgentsCount: 0,
  waitingForAvailability: 0,
  context: {}
}
2023-05-13T18:46:47.964Z INFO [unblocked-agent/lib/Browser] Browser.Launching { name: 'chrome', fullVersion: '112.0.5615.121', context: {} }
2023-05-13T18:46:47.991Z INFO [unblocked-agent/lib/BrowserProcess] chrome.LaunchProcess {
  executablePath: '/home/snow/.cache/ulixee/chrome/112.0.5615.121/chrome',
  launchArguments: [
    '--proxy-bypass-list=<-loopback>',
    '--proxy-server=localhost:38287',
    '--remote-debugging-pipe',
    '--ignore-certificate-errors',
    '--headless',
    '--disable-background-networking',
    '--enable-features=NetworkService,NetworkServiceInProcess',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-breakpad',
    '--disable-client-side-phishing-detection',
    '--disable-domain-reliability',
    '--disable-default-apps',
    '--disable-dev-shm-usage',
    '--disable-extensions',
    '--disable-features=PaintHolding,LazyFrameLoading,DestroyProfileOnBrowserClose,AvoidUnnecessaryBeforeUnloadCheckSync,OutOfBlinkCors,GlobalMediaControls,MediaRouter,DialMediaRouteProvider',
    '--disable-blink-features=AutomationControlled',
    '--disable-hang-monitor',
    '--disable-ipc-flooding-protection',
    '--disable-prompt-on-repost',
    '--disable-renderer-backgrounding',
    '--disable-sync',
    '--force-color-profile=srgb',
    '--disable-skia-runtime-opts',
    '--use-fake-device-for-media-stream',
    '--no-default-browser-check',
    '--metrics-recording-only',
    '--no-first-run',
    '--enable-auto-reload',
    '--password-store=basic',
    '--use-mock-keychain',
    '--allow-running-insecure-content',
    '--window-size=1440,900',
    '--force-webrtc-ip-handling-policy=default_public_interface_only',
    '--no-startup-window',
    '--user-data-dir=/tmp/znLhv-112-0-5615-121',
    '--hide-scrollbars',
    '--mute-audio',
    '--blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4'
  ],
  context: {}
}
2023-05-13T18:46:48.037Z INFO [unblocked-agent/lib/BrowserProcess] chrome.ProcessExited { signal: 'SIGSEGV', context: {} }
2023-05-13T18:46:48.045Z STATS [unblocked-agent/lib/Browser] Browser.LaunchError { chromeStderr: '', context: {} } BrowserLaunchError:
    at BrowserProcess.onChildProcessExit (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/agent/main/lib/BrowserProcess.ts:139:9)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  isSandboxError: false
}
2023-05-13T18:46:48.055Z ERROR [hero-core/connections/ConnectionToHeroClient] ConnectionToClient.HandleRequestError { context: {}, sessionId: undefined, sessionName: undefined } BrowserLaunchError:
    at BrowserProcess.onChildProcessExit (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/agent/main/lib/BrowserProcess.ts:139:9)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
------BROWSER_CREATION_Q--------------------------
    at Queue.run (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Queue.ts:40:19)
    at Pool.getBrowser (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/agent/main/lib/Pool.ts:131:44)
    at Agent.open (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/agent/main/lib/Agent.ts:113:34)
    at async Session.openBrowser (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/lib/Session.ts:255:5)
    at async Function.create (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/lib/Session.ts:901:7)
    at async ConnectionToHeroClient.createSession (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/connections/ConnectionToHeroClient.ts:186:30)
    at async CommandRunner.runFn (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/lib/CommandRunner.ts:36:14)
    at async ConnectionToHeroClient.executeCommand (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/connections/ConnectionToHeroClient.ts:248:12)
    at async ConnectionToHeroClient.handleRequest (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/connections/ConnectionToHeroClient.ts:63:14) {
  message: 'Failed to launch Chrome! Browser exited prematurely (SIGSEGV)',
  isSandboxError: false
}
2023-05-13T18:46:48.060Z INFO [unblocked-agent/lib/Pool] Browser.closed {
  engine: {
    launchArguments: [
      '--proxy-bypass-list=<-loopback>',
      '--proxy-server=localhost:38287',
      '--remote-debugging-pipe',
      '--ignore-certificate-errors',
      '--headless',
      '--disable-background-networking',
      '--enable-features=NetworkService,NetworkServiceInProcess',
      '--disable-background-timer-throttling',
      '--disable-backgrounding-occluded-windows',
      '--disable-breakpad',
      '--disable-client-side-phishing-detection',
      '--disable-domain-reliability',
      '--disable-default-apps',
      '--disable-dev-shm-usage',
      '--disable-extensions',
      '--disable-features=PaintHolding,LazyFrameLoading,DestroyProfileOnBrowserClose,AvoidUnnecessaryBeforeUnloadCheckSync,OutOfBlinkCors,GlobalMediaControls,MediaRouter,DialMediaRouteProvider',
      '--disable-blink-features=AutomationControlled',
      '--disable-hang-monitor',
      '--disable-ipc-flooding-protection',
      '--disable-prompt-on-repost',
      '--disable-renderer-backgrounding',
      '--disable-sync',
      '--force-color-profile=srgb',
      '--disable-skia-runtime-opts',
      '--use-fake-device-for-media-stream',
      '--no-default-browser-check',
      '--metrics-recording-only',
      '--no-first-run',
      '--enable-auto-reload',
      '--password-store=basic',
      '--use-mock-keychain',
      '--allow-running-insecure-content',
      '--window-size=1440,900',
      '--force-webrtc-ip-handling-policy=default_public_interface_only',
      '--no-startup-window',
      '--user-data-dir=/tmp/znLhv-112-0-5615-121',
      '--hide-scrollbars',
      '--mute-audio',
      '--blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4'
    ],
    doesBrowserAnimateScrolling: true,
    engineFetcher: {
      fullVersion: '112.0.5615.121',
      osPlatformName: 'linux',
      executablePathEnvVar: 'CHROME_112_BIN',
      executablePath: '/home/snow/.cache/ulixee/chrome/112.0.5615.121/chrome',
      symlinkVersionDir: '/home/snow/.cache/ulixee/chrome/112.0.5615.138'
    },
    engineOption: {
      id: 'chrome-112-0',
      name: 'chrome',
      majorVersion: 112,
      buildVersion: 5615,
      stablePatchesByOs: {
        mac: [ 137, 121, 49 ],
        win: [ 138, 121, 87, 50 ],
        linux: [ 121, 49 ]
      }
    },
    name: 'chrome',
    fullVersion: '112.0.5615.121',
    executablePath: '/home/snow/.cache/ulixee/chrome/112.0.5615.121/chrome',
    executablePathEnvVar: 'CHROME_112_BIN',
    isInstalled: true,
    isHeaded: false,
    userDataDir: '/tmp/znLhv-112-0-5615-121'
  },
  browserId: '1',
  context: {}
}
2023-05-13T18:46:48.085Z ERROR [hero-core/index] UnhandledRejection { context: {}, sessionId: null, sessionName: undefined } Error [BrowserLaunchError]:
    at BrowserProcess.onChildProcessExit (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/agent/main/lib/BrowserProcess.ts:139:9)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
------BROWSER_CREATION_Q--------------------------
    at Queue.run (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Queue.ts:40:19)
    at Pool.getBrowser (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/agent/main/lib/Pool.ts:131:44)
    at Agent.open (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/agent/main/lib/Agent.ts:113:34)
    at async Session.openBrowser (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/lib/Session.ts:255:5)
    at async Function.create (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/lib/Session.ts:901:7)
    at async ConnectionToHeroClient.createSession (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/connections/ConnectionToHeroClient.ts:186:30)
    at async CommandRunner.runFn (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/lib/CommandRunner.ts:36:14)
    at async ConnectionToHeroClient.executeCommand (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/connections/ConnectionToHeroClient.ts:248:12)
    at async ConnectionToHeroClient.handleRequest (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/core/connections/ConnectionToHeroClient.ts:63:14)
------REMOTE CORE---------------------------------
    at Function.reviver (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/TypeSerializer.ts:249:26)
    at JSON.parse (<anonymous>)
    at Function.parse (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/TypeSerializer.ts:31:17)
    at WsTransportToCore.onMessage (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/net/lib/WsTransportToCore.ts:113:36)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/ws/lib/receiver.js:517:14)
    at /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/ws/lib/receiver.js:468:23
    at /home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/ws/lib/permessage-deflate.js:308:9
------CONNECTION----------------------------------
    at new Resolvable (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Resolvable.ts:19:18)
    at createPromise (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/utils.ts:131:10)
    at PendingMessages.create (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/net/lib/PendingMessages.ts:47:44)
    at ConnectionToHeroCore.sendRequest (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/net/lib/ConnectionToCore.ts:153:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CoreCommandQueue.sendRequest (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/CoreCommandQueue.ts:317:12)
    at async Object.cb (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/CoreCommandQueue.ts:231:16)
    at async Queue.next (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Queue.ts:98:19)
------CORE COMMANDS-------------------------------
    at Queue.run (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Queue.ts:40:19)
    at CoreCommandQueue.run (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/CoreCommandQueue.ts:220:8)
    at Object.cb (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/CoreSessions.ts:35:64)
    at Queue.next (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Queue.ts:98:44)
    at Queue.run (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Queue.ts:43:10)
    at CoreSessions.create (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/CoreSessions.ts:34:8)
    at ConnectionToHeroCore.createSession (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/connections/ConnectionToHeroCore.ts:67:38)
    at Hero._Hero_getCoreSessionOrReject (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/Hero.ts:686:10)
    at Hero.get activeTab [as activeTab] (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/Hero.ts:174:33)
    at Hero.goto (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/Hero.ts:465:17)
------AGENT QUEUE---------------------------------
    at Queue.run (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/commons/lib/Queue.ts:40:19)
    at CoreSessions.create (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/CoreSessions.ts:34:8)
    at ConnectionToHeroCore.createSession (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/connections/ConnectionToHeroCore.ts:67:38)
    at Hero._Hero_getCoreSessionOrReject (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/Hero.ts:686:10)
    at Hero.get activeTab [as activeTab] (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/Hero.ts:174:33)
    at Hero.goto (/home/snow/Desktop/fiverr/AP_Crawler/apcrawler/node_modules/client/lib/Hero.ts:465:17)
    at Index.$extract (file:///home/snow/Desktop/fiverr/AP_Crawler/apcrawler/dist/index.js:8:28)
    at Index.exec (file:///home/snow/Desktop/fiverr/AP_Crawler/apcrawler/dist/hero_client.js:52:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  message: 'Ulixee Cloud failed to launch Chrome - Failed to launch Chrome! Browser exited prematurely (SIGSEGV). See Cloud console logs for details.',
  isSandboxError: false
}
^C2023-05-13T18:46:51.184Z STATS [cloud/lib/CloudNode] CloudNode.Closing { closeDependencies: true, context: {} }
2023-05-13T18:46:51.187Z STATS [hero-core/connections/ConnectionToHeroClient] ConnectionToClient.Disconnecting { context: {} }
2023-05-13T18:46:51.189Z STATS [hero-core/connections/ConnectionToHeroClient] ConnectionToClient.Disconnected { context: {} }
2023-05-13T18:46:51.194Z STATS [net/lib/ConnectionToCore] ConnectionToCore.Disconnecting { host: 'direct', context: {} }
2023-05-13T18:46:51.197Z STATS [net/lib/ConnectionToCore] ConnectionToCore.Disconnected { host: 'direct', context: {} }
2023-05-13T18:46:51.199Z INFO [hero-core/index] Core.shutdown { context: {} }
2023-05-13T18:46:51.200Z STATS [hero-core/connections/ConnectionToHeroClient] ConnectionToClient.Disconnecting { context: {} }
2023-05-13T18:46:51.202Z STATS [unblocked-agent/lib/Pool] Pool.Closing { browsers: 0, context: {} }
2023-05-13T18:46:51.203Z INFO [unblocked-agent/lib/Agent] Agent.Closing { context: { sessionId: 'dzTjDmn7DXs7etiPtT_3K' } }
2023-05-13T18:46:51.209Z INFO [unblocked-agent/lib/Pool] ReleasingAgent {
  maxConcurrentAgents: 10,
  activeAgentsCount: 0,
  waitingForAvailability: 0,
  context: {}
}
2023-05-13T18:46:51.210Z STATS [unblocked-agent/lib/Agent] Agent.Closed { context: { sessionId: 'dzTjDmn7DXs7etiPtT_3K' } }
2023-05-13T18:46:51.210Z STATS [hero-core/connections/ConnectionToHeroClient] ConnectionToClient.Disconnected { context: {} }
2023-05-13T18:46:51.210Z STATS [unblocked-agent/lib/Pool] Pool.Closed { errors: [], context: {} }
2023-05-13T18:46:51.212Z INFO [hero-core/index] Core.shutdownComplete { context: {} }
2023-05-13T18:46:51.213Z STATS [cloud/lib/CloudNode] CloudNode.Closed { context: {} }
2023-05-13T18:46:51.214Z STATS [net/lib/ConnectionToCore] ConnectionToCore.Disconnecting { host: 'ws://localhost:6450/hero', context: {} }
2023-05-13T18:46:51.223Z STATS [net/lib/ConnectionToCore] ConnectionToCore.Disconnected { host: 'ws://localhost:6450/hero', context: {} }
`

**Comment by blakebyrnes** [comment]
Can you see if you can open the Chrome at that path (/home/snow/.cache/ulixee/chrome/112.0.5615.121/chrome)

`/home/snow/.cache/ulixee/chrome/112.0.5615.121/chrome --headless --dump-dom https://ulixee.org`

**Comment by benhichem** [comment]
no  the chrome did no open !

**Comment by benhichem** [comment]
i have fixed that issues by reinstalling chrome 
by running npm i @ulixee/chrome-112-0 and now am able to start Hero ! 
but now am getting this if you do not mind expla
![image](https://github.com/ulixee/hero/assets/77390862/cfe076fa-59c2-4608-ae54-ec31f90fe57b)

**Comment by blakebyrnes** [comment]
I think that one is likely related to some code. Can you share the snippet failing or a session database? I'm on discord if you can't share the code for the part failing

**Comment by benhichem** [comment]
sure mate what is your discord ?
