### ISSUE TITLE
Use real extensions

### ISSUE THREAD

**Issue by NN-Binary** [ulixee/hero#266]
Hi, I would like to add uBlock origin, is there a way?

**Comment by blakebyrnes** [comment]
Kind of, but it's a bit tricky. Hero runs in incognito mode, which makes activating extensions a pain. You can turn off incognito mode, but that restricts each chrome instance to a single Hero session, or you can automate turning on the extension in incognito mode by navigating to the extension pages as the beginning of every Hero session.

You'll need to use a plugin (https://ulixee.org/docs/hero/plugins/core-plugins) to add the chrome launch args to activate the extension. You might also need to remove '--disable-extensions' and a few other conflicting ones from the launchArgs.

```
class CoreHelloPlugin extends CorePlugin {
    static get id() { return 'ublock-plugin'; }

    onNewBrowser(browser, launchArgs) {
        launchArgs.push(
            `--disable-extensions-except=...`,
            `--load-extension=...`,
        )

    }
}
HeroCore.use(CoreHelloPlugin);
```

**Comment by NN-Binary** [comment]
Thank you!

I think this does not work
```

        let DirTest = '/home/user/extensions/consentomatic/';
        class CoreHelloPlugin extends CorePlugin {
            
            onNewBrowser(browser, launchArgs) {
                launchArgs.push(
                    `--disable-extensions-except=` + DirTest,
                    `--load-extension=` + DirTest,
                )
            }
            
        }



```

There is no error whatsoever, I can check also in `chrome://version` that the flag does not seem to be passed
The path is correct, when loading it manually as dev mode, it does work.

**Comment by blakebyrnes** [comment]
Sorry, I used bad args for that example. API signature is `  onNewBrowser?(browser: IBrowser, userConfig: IBrowserUserConfig): void;`

should be `browser.engine.launchArguments.push(...`

**Comment by NN-Binary** [comment]
Thank you, it works to load the extension, now an issue is that I can't seem to browse programmatically on chrome://extensions

It instantly crash:
`2024-06-12T12:52:25.007Z ERROR [hero-core/index] UnhandledRejection { context: {}, sessionId: null, sessionName: undefined } DisconnectedError: This transport has been disconnected (host: ws://localhost:43369/hero)`

**Comment by blakebyrnes** [comment]
Is there any other errors in the logs that say why chrome crashed (or hero crashed)?

**Comment by NN-Binary** [comment]
```
2024-06-12T13:16:30.160Z ERROR [hero-core/index] UnhandledRejection { context: {}, sessionId: null, sessionName: undefined } DisconnectedError: This transport has been disconnected (host: ws://localhost:38185/hero)
    at ConnectionToHeroCore.onConnectionTerminated (/home/user/MARKETING/node_modules/net/lib/ConnectionToCore.ts:241:33)
    at WsTransportToCore.finalHandler (/home/user/MARKETING/node_modules/commons/lib/EventSubscriber.ts:46:14)
    at Object.onceWrapper (node:events:634:26)
    at WsTransportToCore.emit (node:events:519:28)
    at WsTransportToCore.emit (/home/user/MARKETING/node_modules/commons/lib/TypedEventEmitter.ts:158:18)
    at WsTransportToCore.disconnect (/home/user/MARKETING/node_modules/net/lib/WsTransportToCore.ts:60:10)
    at WebSocket.finalHandler (/home/user/MARKETING/node_modules/commons/lib/EventSubscriber.ts:46:14)
    at Object.onceWrapper (node:events:634:26)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (/home/user/MARKETING/node_modules/ws/lib/websocket.js:246:10)
------CONNECTION----------------------------------
  at new Resolvable (/home/user/MARKETING/node_modules/commons/lib/Resolvable.ts:19:18)
    at createPromise (/home/user/MARKETING/node_modules/commons/lib/utils.ts:140:10)
    at PendingMessages.create (/home/user/MARKETING/node_modules/net/lib/PendingMessages.ts:47:44)
    at ConnectionToHeroCore.sendRequest (/home/user/MARKETING/node_modules/net/lib/ConnectionToCore.ts:158:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CoreCommandQueue.sendRequest (/home/user/MARKETING/node_modules/client/lib/CoreCommandQueue.ts:317:12)
    at async Object.cb (/home/user/MARKETING/node_modules/client/lib/CoreCommandQueue.ts:231:16)
    at async Queue.next (/home/user/MARKETING/node_modules/commons/lib/Queue.ts:188:19)
------CORE COMMANDS-------------------------------
    at Queue.run (/home/user/MARKETING/node_modules/commons/lib/Queue.ts:63:19)
    at CoreCommandQueue.run (/home/user/MARKETING/node_modules/client/lib/CoreCommandQueue.ts:220:8)
    at CoreTab.goto (/home/user/MARKETING/node_modules/client/lib/CoreTab.ts:265:36)
    at Tab.goto (/home/user/MARKETING/node_modules/client/lib/Tab.ts:201:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SpawnProfile (/home/user/MARKETING/program/browse.js:716:9)

```

That's right after `goTo` action.

**Comment by blakebyrnes** [comment]
If you turn on DEBUG=ulx* on the command line, you should get more verbose logging (this is on core side). I don't see any clues in this snippet.

**Comment by NN-Binary** [comment]
```
d: [32m'D3AFFFAB028BBDC1BAB5CC4B3B0E5637'[39m,
  context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m }
}
2024-06-12T13:22:14.632Z STATS [unblocked-agent/lib/DevtoolsSessionLogger] receive:Runtime.evaluate {
  pageId: [32m'EE0BFA582D29C3A7EC6FC22F2FC6F94D'[39m,
  frameId: [32m'EE0BFA582D29C3A7EC6FC22F2FC6F94D'[39m,
  messageId: [33m87[39m,
  result: { result: { type: [32m'undefined'[39m } },
  devtoolsSessionId: [32m'D3AFFFAB028BBDC1BAB5CC4B3B0E5637'[39m,
  context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m }
}
2024-06-12T13:22:14.641Z WARN [unblocked-agent/lib/BrowserProcess] chrome.stderr {
  message: [32m'[0612/212214.641317:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)'[39m,
  context: {},
  sessionId: [1mnull[22m,
  sessionName: [90mundefined[39m
}
2024-06-12T13:22:14.641Z WARN [unblocked-agent/lib/BrowserProcess] chrome.stderr {
  message: [32m'[0612/212214.641363:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)'[39m,
  context: {},
  sessionId: [1mnull[22m,
  sessionName: [90mundefined[39m
}
2024-06-12T13:22:14.666Z INFO [unblocked-agent/lib/PipeTransport] PipeTransport.Closed { context: {} }
2024-06-12T13:22:14.667Z INFO [unblocked-agent/lib/BrowserProcess] chrome.ProcessExited { context: {} }
2024-06-12T13:22:14.668Z INFO [unblocked-agent/lib/Agent] Agent.Closing { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.669Z INFO [unblocked-agent/lib/BrowserContext] BrowserContext.Closing {
  context: {
    sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m,
    browserContextId: [32m'91B21D6427315D75FC021BF0D8CF3A91'[39m
  }
}
2024-06-12T13:22:14.672Z STATS [hero-core/lib/Tab] Tab.Closing { context: { tabId: [33m1[39m, sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.672Z STATS [unblocked-agent/lib/BrowserContext] BrowserContext.Closed 3ms {
  context: {
    sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m,
    browserContextId: [32m'91B21D6427315D75FC021BF0D8CF3A91'[39m
  }
}
2024-06-12T13:22:14.681Z STATS [hero-core/lib/FrameEnvironment] FrameEnvironment.Closing {
  context: { tabId: [33m1[39m, sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m, frameId: [33m1[39m }
}
2024-06-12T13:22:14.681Z STATS [hero-core/lib/FrameEnvironment] FrameEnvironment.Closed {
  context: { tabId: [33m1[39m, sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m, frameId: [33m1[39m }
}
2024-06-12T13:22:14.682Z STATS [unblocked-agent-mitm/handlers/RequestSession] MitmRequestSession.Closing { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.682Z INFO [unblocked-agent-mitm-socket/lib/MitmSocketSession] ProxyIpcHandler.Closing { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.682Z INFO [unblocked-agent-mitm-socket/index] MitmSocket.Closing { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.682Z STATS [unblocked-agent-mitm/lib/SocketPool] Socket closed {
  context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m, origin: [32m'hoody.com:443'[39m }
}
2024-06-12T13:22:14.682Z STATS [unblocked-agent-mitm-socket/index] MitmSocket.Closed { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.682Z INFO [unblocked-agent-mitm-socket/index] MitmSocket.Closing { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.682Z STATS [unblocked-agent-mitm/lib/SocketPool] Socket closed {
  context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m, origin: [32m'www.google.com:443'[39m }
}
2024-06-12T13:22:14.683Z STATS [unblocked-agent-mitm-socket/index] MitmSocket.Closed 1ms { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.683Z INFO [unblocked-agent-mitm-socket/index] MitmSocket.Closing { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.683Z STATS [unblocked-agent-mitm/lib/SocketPool] Socket closed {
  context: {
    sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m,
    origin: [32m'stackoverflow.com:443'[39m
  }
}
2024-06-12T13:22:14.683Z STATS [unblocked-agent-mitm-socket/index] MitmSocket.Closed { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.683Z STATS [unblocked-agent-mitm-socket/lib/MitmSocketSession] ProxyIpcHandler.Closed 1ms { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.683Z STATS [unblocked-agent-mitm/handlers/RequestSession] MitmRequestSession.Closed 1ms { errors: [], context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.683Z INFO [unblocked-agent-mitm/lib/MitmProxy] MitmProxy.Closing { context: {} }
2024-06-12T13:22:14.684Z STATS [unblocked-agent-mitm/lib/MitmProxy] MitmProxy.Closed 1ms { closeErrors: [], context: {} }
2024-06-12T13:22:14.685Z INFO [unblocked-agent/lib/Pool] Pool.ReleasingAgent {
  maxConcurrentAgents: [33m10[39m,
  activeAgentsCount: [33m0[39m,
  waitingForAvailability: [33m0[39m,
  context: {}
}
2024-06-12T13:22:14.685Z STATS [unblocked-agent/lib/Agent] Agent.Closed 17ms { context: { sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.685Z STATS [hero-core/lib/Tab] emit:close { context: { tabId: [33m1[39m, sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m } }
2024-06-12T13:22:14.685Z STATS [hero-core/lib/Tab] Tab.Closed 13ms {
  errors: [
    [32m"TypeError: Cannot read properties of null (reading 'finalFlush')"[39m
  ],
  context: { tabId: [33m1[39m, sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m }
}
2024-06-12T13:22:14.685Z STATS [hero-core/lib/CommandRecorder] Command.done 242ms {
  id: [33m1[39m,
  context: { tabId: [33m1[39m, sessionId: [32m'zhrx7jKJh0g7eyy3bS0kd'[39m, frameId: [33m1[39m }
} CanceledPromiseError: Cancel Pending Promise. Frame closed.
    at FrameNavigationsObserver.cancelWaiting (/home/user/MARKETING/agent/main/lib/FrameNavigationsObserver.ts:128:24)
    at Frame.close (/home/user/MARKETING/agent/main/lib/Frame.ts:204:30)
    at FramesManager.close (/home/user/MARKETING/agent/main/lib/FramesManager.ts:204:13)
    at Page.didClose (/home/user/MARKETING/agent/main/lib/Page.ts:559:26)
    at /home/user/MARKETING/agent/main/lib/BrowserContext.ts:349:47
    at Array.map (<anonymous>)
    at BrowserContext.close (/home/user/MARKETING/agent/main/lib/BrowserContext.ts:349:36)
    at Agent.close (/home/user/MARKETING/agent/main/lib/Agent.ts:174:34)
    at Pool.onBrowserClosed (/home/user/MARKETING/agent/main/lib/Pool.ts:295:70)
    at /home/user/MARKETING/agent/main/lib/Pool.ts:171:53
------LOCATION------------------------------------
  at new Resolvable (/home/user/MARKETING/node_modules/[4mcommons[24m/lib/Resolvable.ts:19:18)
    at createPromise (/home/user/MARKETING/node_modules/[4mcommons[24m/lib/utils.ts:140:10)
    at FrameNavigations.onNavigationRequested (/home/user/MARKETING/agent/main/lib/FrameNavigations.ts:148:44)
    at Page.goto (/home/user/MARKETING/agent/main/lib/Page.ts:309:51)
    at Tab.goto (/home/user/MARKETING/node_modules/[4mcore[24m/lib/Tab.ts:519:28)
    at CommandRecorder.runCommandFn (/home/user/MARKETING/node_modules/[4mcore[24m/lib/CommandRecorder.ts:90:32)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async CommandRunner.runFn (/home/user/MARKETING/node_modules/[4mcore[24m/lib/CommandRunner.ts:36:14)
    at async ConnectionToHeroClient.executeCommand (/home/user/MARKETING/node_modules/[4mcore[24m/connections/ConnectionToHeroClient.ts:258:12)
    at async ConnectionToHeroClient.handleRequest (/home/user/MARKETING/node_modules/[4mcore[24m/connections/ConnectionToHeroClient.ts:66:14)
```

**Comment by NN-Binary** [comment]
I've also tried to create another tab first then browse with that tab, manual fake click too... all of them crash the instance right away, except when it's done manually, then it works.
