### ISSUE TITLE
SqliteError: attempt to write a readonly database

### ISSUE THREAD

**Issue by NN-Binary** [ulixee/hero#292]
Hero can't start anymore, I've emptied ~/.cache/ulixee without success.

It was all working until it didn't.
Instances are started with userAgent: ~ chrome >= 125 && windows >= 10

```
SqliteError: attempt to write a readonly database
    at Database.exec (/home/user/hero/program/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at new SqliteTable (/home/user/hero/program/node_modules/commons/lib/SqliteTable.ts:26:15)
    at new CertificatesTable (/home/user/hero/program/node_modules/core/models/CertificatesTable.ts:8:5)
    at new NetworkDb (/home/user/hero/program/node_modules/core/dbs/NetworkDb.ts:24:25)
    at new HeroCore (/home/user/hero/program/node_modules/core/index.ts:104:22)
    at new CloudNode (/home/user/hero/program/cloud/main/lib/CloudNode.ts:137:21)
    at GetHeroPlayground (/home/user/hero/program/browse.js:1739:17)
    at SpawnBrowser (/home/user/hero/program/browse.js:1776:30)
    at async ProcessMessage (/home/user/hero/program/browse.js:3485:26)
    at async MessagePort.<anonymous> (/home/user/hero/program/browse.js:3657:18) {
  code: 'UNKNOWN_SQLITE_ERROR_1544'
}
```

**Comment by NN-Binary** [comment]
Solved, it was in `/tmp/.ulixee`
